pipeline
{
    agent {
        label 'jenkins-test'
    }
    parameters {
        string defaultValue: 'SINGH', name: 'LASTNAME'
    }

    environment {
        NAME = 'NISHU '
    }

    tools {
        maven 'mymaven'
    }
    stages {
        stage('build')
    {
            steps {
                sh 'mvn clean package'
                echo "hello $NAME ${params.LASTNAME}"
            }
    }
        stage('test') {
            parallel {
                stage('testA') {
                    steps {
                        echo 'This is test A'
                    }
                }
                stage('testB') {
                    steps {
                        echo 'this is test B'
                    }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}
