pipeline
{
    agent {
        label 'jenkins-test'
    }
    parameters {
  string defaultValue: 'SINGH', name: 'LASTNAME'
}


    environment {
        NAME = "NISHU "
    }

    tools {
        maven 'mymaven'
    }
    stages {
        stage('build')
    {
            steps {
                sh 'mvn clean package'
                echo "hello $NAME ${params.LASTNAME}"
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
    }
    }
}
