pipeline
{
    agent {
        label 'jenkins-test'
    }
    stages {
        stage('build')
    {
            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    archiveArtfacts artifacts: '**/target/*.war'
                }
            }
    }
    }
}